platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
inputs:
- name: cg-diagrams-source
outputs:
- name: cg-diagrams-compiled
run:
  dir: cg-diagrams-source
  path: ci/build.sh
